export const GET_AVAILABLE_DEVICES = 'GET_AVAILABLE_DEVICES';
export const GET_AVAILABLE_DEVICES_FAILURE = 'GET_AVAILABLE_DEVICES_FAILURE';
export const GET_AVAILABLE_DEVICES_SUCCESS = 'GET_AVAILABLE_DEVICES_SUCCESS';
