export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';

export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM_FAILURE';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
