export const SEARCH_TRACKS = 'SEARCH_TRACKS';
export const SEARCH_TRACKS_FAILURE = 'SEARCH_TRACKS_FAILURE';
export const SEARCH_TRACKS_SUCCESS = 'SEARCH_TRACKS_SUCCESS';

export const CLEAR_SEARCH = 'CLEAR_SEARCH';
