export const LOAD = 'LOAD';

export const SPOTIFY_LOGIN = 'SPOTIFY_LOGIN';
export const SPOTIFY_LOGIN_FAILURE = 'SPOTIFY_LOGIN_FAILURE';
export const SPOTIFY_LOGIN_SUCCESS = 'SPOTIFY_LOGIN_SUCCESS';

export const SPOTIFY_LOGOUT = 'SPOTIFY_LOGOUT';

export const LISTJOCKEY_LOGIN = 'LISTJOCKEY_LOGIN';
export const LISTJOCKEY_LOGIN_FAILURE = 'LISTJOCKEY_LOGIN_FAILURE';
export const LISTJOCKEY_LOGIN_SUCCESS = 'LISTJOCKEY_LOGIN_SUCCESS';

export const LISTJOCKEY_LOGOUT = 'LISTJOCKEY_LOGOUT';
export const LISTJOCKEY_LOGOUT_FAILURE = 'LISTJOCKEY_LOGOUT_FAILURE';
export const LISTJOCKEY_LOGOUT_SUCCESS = 'LISTJOCKEY_LOGOUT_SUCCESS';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_TOKEN_FAILURE = 'UPDATE_TOKEN_FAILURE';
export const UPDATE_TOKEN_SUCCESS = 'UPDATE_TOKEN_SUCCESS';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
