export const GET_ROOM = 'GET_ROOM';
export const GET_ROOM_FAILURE = 'GET_ROOM_FAILURE';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_FAILURE = 'JOIN_ROOM_FAILURE';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';

export const LEAVE_ROOM = 'LEAVE_ROOM';
export const LEAVE_ROOM_FAILURE = 'LEAVE_ROOM_FAILURE';
export const LEAVE_ROOM_SUCCESS = 'LEAVE_ROOM_SUCCESS';
